"""candidate profile payload

Revision ID: a27f58a5e51c
Revises: cbb284f817e8
Create Date: 2026-08-06 15:53:30.081593
"""

from typing import Sequence, Union

import sqlalchemy as sa

import core.db.crypto  # custom column types (EncryptedString)
from alembic import op

revision: str = "a27f58a5e51c"
down_revision: Union[str, None] = "cbb284f817e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cv_profile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "candidate_payload", core.db.crypto.EncryptedString(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cv_profile", schema=None) as batch_op:
        batch_op.drop_column("candidate_payload")

    # ### end Alembic commands ###
