"""initial schema

Revision ID: be8b1a8784fd
Revises:
Create Date: 2026-07-23 21:15:21.957064
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

import core.db.crypto  # custom column types (EncryptedString)
from alembic import op

revision: str = "be8b1a8784fd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "normalized_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("ats_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("careers_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("glassdoor_rating", sa.Float(), nullable=True),
        sa.Column("had_layoffs", sa.Boolean(), nullable=False),
        sa.Column("sponsors_visa", sa.Boolean(), nullable=True),
        sa.Column("blacklisted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("company", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_company_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_company_normalized_name"), ["normalized_name"], unique=False
        )

    op.create_table(
        "cv_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", core.db.crypto.EncryptedString(), nullable=True),
        sa.Column("phone", core.db.crypto.EncryptedString(), nullable=True),
        sa.Column("linkedin", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("github", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("payload", core.db.crypto.EncryptedString(), nullable=True),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "suppression",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("suppression", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_suppression_email_hash"), ["email_hash"], unique=True
        )

    op.create_table(
        "contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", core.db.crypto.EncryptedString(), nullable=True),
        sa.Column("email_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "email_confidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("email_verified", sa.Boolean(), nullable=True),
        sa.Column("linkedin", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contact", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contact_email_hash"), ["email_hash"], unique=False
        )

    op.create_table(
        "job_posting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("remote", sa.Boolean(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("salary_min", sa.Float(), nullable=True),
        sa.Column("salary_max", sa.Float(), nullable=True),
        sa.Column("salary_currency", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("employment_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("date_posted", sa.DateTime(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("dedup_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_duplicate", sa.Boolean(), nullable=False),
        sa.Column("canonical_job_id", sa.Integer(), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("match_explanation", sa.JSON(), nullable=True),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("ghost_score", sa.Float(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["canonical_job_id"],
            ["job_posting.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_id", name="uq_source_job"),
    )
    with op.batch_alter_table("job_posting", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_posting_company_name"), ["company_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_posting_dedup_key"), ["dedup_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_posting_source"), ["source"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_posting_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "application",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("job_dedup_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cv_profile_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SAVED",
                "APPLIED",
                "SCREENING",
                "INTERVIEW",
                "OFFER",
                "REJECTED",
                "WITHDRAWN",
                name="applicationstatus",
            ),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.Column("next_follow_up_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cv_profile_id"],
            ["cv_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_posting.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_dedup_key", "cv_profile_id", name="uq_application"),
    )
    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_application_job_dedup_key"), ["job_dedup_key"], unique=False
        )

    op.create_table(
        "email_draft",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", core.db.crypto.EncryptedString(), nullable=True),
        sa.Column("recipient_email", core.db.crypto.EncryptedString(), nullable=True),
        sa.Column("recipient_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("company", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("gmail_draft_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_posting.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_draft")
    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_application_job_dedup_key"))

    op.drop_table("application")
    with op.batch_alter_table("job_posting", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_posting_source_id"))
        batch_op.drop_index(batch_op.f("ix_job_posting_source"))
        batch_op.drop_index(batch_op.f("ix_job_posting_dedup_key"))
        batch_op.drop_index(batch_op.f("ix_job_posting_company_name"))

    op.drop_table("job_posting")
    with op.batch_alter_table("contact", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contact_email_hash"))

    op.drop_table("contact")
    with op.batch_alter_table("suppression", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_suppression_email_hash"))

    op.drop_table("suppression")
    op.drop_table("cv_profile")
    with op.batch_alter_table("company", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_company_normalized_name"))
        batch_op.drop_index(batch_op.f("ix_company_name"))

    op.drop_table("company")
    # ### end Alembic commands ###
