"""company.had_layoffs nullable (unknown != no layoffs)

Revision ID: cbb284f817e8
Revises: be8b1a8784fd
Create Date: 2026-07-25 06:04:22.645218
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "cbb284f817e8"
down_revision: Union[str, None] = "be8b1a8784fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company", schema=None) as batch_op:
        batch_op.alter_column("had_layoffs", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company", schema=None) as batch_op:
        batch_op.alter_column("had_layoffs", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###
