"""
Local storage for drafts and export to JSON/ZIP
"""

import json
import os
from datetime import datetime
from typing import List, Dict, Any
from zipfile import ZipFile
from .models import EmailDraft, WhatsAppDraft, CVProfile, JobPosting


class LocalStorage:
    """Manage local storage of drafts and artifacts"""

    def __init__(self, storage_dir: str = "careeragent_data"):
        self.storage_dir = storage_dir
        self._ensure_directories()

    def _ensure_directories(self):
        """Create storage directories if they don't exist"""
        dirs = [
            self.storage_dir,
            os.path.join(self.storage_dir, "email_drafts"),
            os.path.join(self.storage_dir, "whatsapp_drafts"),
            os.path.join(self.storage_dir, "cv_profiles"),
            os.path.join(self.storage_dir, "job_postings"),
            os.path.join(self.storage_dir, "exports"),
        ]

        for dir_path in dirs:
            os.makedirs(dir_path, exist_ok=True)

    def save_email_draft(self, draft: EmailDraft) -> str:
        """Save email draft as JSON"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"email_{draft.company}_{timestamp}.json"
        filepath = os.path.join(self.storage_dir, "email_drafts", filename)

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(draft.dict(), f, indent=2, default=str)

        return filepath

    def save_whatsapp_draft(self, draft: WhatsAppDraft) -> str:
        """Save WhatsApp draft as JSON"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"whatsapp_{draft.company}_{timestamp}.json"
        filepath = os.path.join(self.storage_dir, "whatsapp_drafts", filename)

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(draft.dict(), f, indent=2, default=str)

        return filepath

    def save_cv_profile(self, profile: CVProfile) -> str:
        """Save CV profile as JSON"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"cv_profile_{timestamp}.json"
        filepath = os.path.join(self.storage_dir, "cv_profiles", filename)

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(profile.dict(), f, indent=2, default=str)

        return filepath

    def save_job_posting(self, job: JobPosting) -> str:
        """Save job posting as JSON"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"job_{job.company}_{timestamp}.json"
        filepath = os.path.join(self.storage_dir, "job_postings", filename)

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(job.dict(), f, indent=2, default=str)

        return filepath

    def export_to_markdown(self, draft: EmailDraft) -> str:
        """Export email draft as markdown"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"email_{draft.company}_{timestamp}.md"
        filepath = os.path.join(self.storage_dir, "exports", filename)

        markdown = f"""# Email Draft for {draft.job_title} at {draft.company}

**Created:** {draft.created_at}
**Recipient:** {draft.recipient_name or "TBD"}
**To:** {draft.recipient_email or "TBD"}

---

## Subject

{draft.subject}

---

## Body

{draft.body}

---

## Metadata

- **Word Count:** {draft.word_count}
- **Job Title:** {draft.job_title}
- **Company:** {draft.company}
- **Gmail Draft ID:** {draft.gmail_draft_id or "Not created"}

---

## Personalization Plan

**Angle:** {draft.personalization_plan.angle if draft.personalization_plan else "N/A"}

**Technical Hook:** {draft.personalization_plan.technical_hook if draft.personalization_plan else "N/A"}

**Impact Hook:** {draft.personalization_plan.impact_hook if draft.personalization_plan else "N/A"}

**Company Hook:** {draft.personalization_plan.company_hook if draft.personalization_plan else "N/A"}

---

*Generated by CareerAgent - Local AI Career Agent*
"""

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(markdown)

        return filepath

    def create_export_zip(self, name: str = "careeragent_export") -> str:
        """Create ZIP archive of all artifacts"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        zip_filename = f"{name}_{timestamp}.zip"
        zip_filepath = os.path.join(self.storage_dir, "exports", zip_filename)

        with ZipFile(zip_filepath, "w") as zipf:
            # Add all JSON files
            for root, dirs, files in os.walk(self.storage_dir):
                for file in files:
                    if file.endswith((".json", ".md")):
                        file_path = os.path.join(root, file)
                        arcname = os.path.relpath(file_path, self.storage_dir)
                        zipf.write(file_path, arcname)

        return zip_filepath

    def list_email_drafts(self) -> List[str]:
        """List all saved email drafts"""
        draft_dir = os.path.join(self.storage_dir, "email_drafts")
        return [f for f in os.listdir(draft_dir) if f.endswith(".json")]

    def load_email_draft(self, filename: str) -> EmailDraft:
        """Load email draft from JSON"""
        filepath = os.path.join(self.storage_dir, "email_drafts", filename)
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)
        return EmailDraft(**data)
